/**
 * Maa Enterprises — Cyber Cafe & Online Service Center
 * PART 3 — Dynamic Service Data Layer & Catalog Engine
 * Author: Senior Frontend Architect
 */

'use strict';

/**
 * Service Categories Definition
 */
const SERVICE_CATEGORIES = Object.freeze([
  "All Services",
  "Government Jobs & Recruitment",
  "College & School Admissions",
  "Identity & Legal",
  "Certificates",
  "Banking & Bill Payments",
  "Business Services",
  "Other Online Services"
]);

/**
 * Complete Service Catalog Dataset (58 Verified Baseline Records)
 */
const SERVICES_DATA = Object.freeze([
  {"id": "gov-job-general", "name": "Government Job Application Assistance", "category": "Government Jobs & Recruitment", "icon": "briefcase", "shortDescription": "Assistance in filling and submitting central and state government recruitment applications.", "description": "We assist candidates with checking eligibility criteria, filling online application forms, uploading required documents, and completing registration fees for central and state recruitment portals.", "keywords": ["sarkari", "naukri", "recruitment", "job", "form"], "documents": ["Educational Certificates (10th/12th/Degree)", "Aadhaar Card", "Passport Photo & Signature", "Caste/Domicile Certificate (if applicable)"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "ssc-recruitment", "name": "SSC Recruitment Form Assistance", "category": "Government Jobs & Recruitment", "icon": "file-text", "shortDescription": "Online form submission for SSC CGL, CHSL, MTS, GD Constable, and CPO examinations.", "description": "Complete guidance for Staff Selection Commission (SSC) OTR registration, application filing, exam center selection, and photo/signature dimension verification.", "keywords": ["ssc", "cgl", "chsl", "mts", "gd constable"], "documents": ["SSC Registration ID/Password", "10th/12th/Degree Certificates", "Photo & Signature", "Photo ID Proof"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "railway-recruitment", "name": "Railway Recruitment Form (RRB / RRC)", "category": "Government Jobs & Recruitment", "icon": "navigation", "shortDescription": "Application assistance for Railway NTPC, Group D, ALP, and Technician posts.", "description": "Assistance with RRB and RRC online applications, trade/post selection, zone choices, document uploads, and payment receipt generation.", "keywords": ["railway", "rrb", "rrc", "ntpc", "group d", "alp"], "documents": ["10th Marksheet", "ITI / Diploma / Degree Certificate", "Aadhaar Card", "Passport Photo & Signature"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "banking-recruitment", "name": "Banking Recruitment Form (IBPS / SBI / RBI)", "category": "Government Jobs & Recruitment", "icon": "dollar-sign", "shortDescription": "Application filing for Bank PO, Clerk, SO, and Assistant examinations.", "description": "Guidance for IBPS, SBI, and RBI recruitment, including declaration scanning, thumb impression upload, and preference selection.", "keywords": ["bank", "ibps", "sbi", "rbi", "po", "clerk"], "documents": ["Graduation Details", "Passport Photo & Signature", "Left Thumb Impression", "Handwritten Declaration"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "police-recruitment", "name": "Police & Paramilitary Recruitment Form", "category": "Government Jobs & Recruitment", "icon": "shield", "shortDescription": "Application support for Bihar Police, SI, Constable, CRPF, CISF, and BSF vacancies.", "description": "Assistance in filling state police and central paramilitary application forms, physical criteria record entries, and fee payment.", "keywords": ["police", "bihar police", "si", "daroga", "constable", "crpf"], "documents": ["10th/12th/Graduation Certificates", "Aadhaar Card", "Bihar Domicile Certificate", "Passport Photo & Signature"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "defence-recruitment", "name": "Defence Services Form (Army / Navy / Air Force / NDA)", "category": "Government Jobs & Recruitment", "icon": "award", "shortDescription": "Registration assistance for Agniveer Army, Navy, Air Force, NDA, and CDS forms.", "description": "Guidance for joining the Armed Forces via Agniveer schemes, UPSC NDA, and CDS portals. We help verify eligibility and rally/exam center choices.", "keywords": ["army", "navy", "airforce", "agniveer", "nda", "cds"], "documents": ["10th & 12th Marksheets", "Aadhaar Card", "Passport Photo & Signature", "Residential Certificate"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "bihar-gov-recruitment", "name": "Bihar State Government Recruitment (BPSC / BSSC / BPSSC)", "category": "Government Jobs & Recruitment", "icon": "check-square", "shortDescription": "Application filing for BPSC Civil Services, BSSC Inter/CGL, and BPSSC vacancies.", "description": "Assistance for Bihar state examinations including BPSC, BSSC Inter Level, and BPSSC Sub-Inspector with proper domicile and reservation verification.", "keywords": ["bpsc", "bssc", "bpssc", "bihar ssc", "inter level"], "documents": ["Educational Certificates", "Bihar Domicile Certificate", "Caste/NCL/EWS Certificate", "Photo & Signatures (Hindi/English)"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "teacher-recruitment", "name": "Teacher Recruitment Form (CTET / STET / BPSC TRE)", "category": "Government Jobs & Recruitment", "icon": "book-open", "shortDescription": "Application assistance for CTET, Bihar STET, and BPSC Teacher Recruitment Exams.", "description": "Assistance for teaching eligibility tests and recruitment with subject selection, D.El.Ed / B.Ed qualification entry, and roll number verification.", "keywords": ["ctet", "stet", "bpsc tre", "teacher", "dled", "bed"], "documents": ["D.El.Ed / B.Ed Marksheet", "Graduation Marksheet", "CTET/STET Scorecard", "Aadhaar Card", "Photo & Signature"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "admit-card-download", "name": "Recruitment Admit Card Download & Printout", "category": "Government Jobs & Recruitment", "icon": "download", "shortDescription": "Instant search, retrieval, and high-quality printout of examination admit cards.", "description": "Assistance in retrieving examination hall tickets from central and state portals with crisp black/white and color printout options.", "keywords": ["admit card", "hall ticket", "call letter", "exam printout"], "documents": ["Application / Registration Number", "Date of Birth / Password"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "result-scorecard-download", "name": "Exam Result & Scorecard Download Assistance", "category": "Government Jobs & Recruitment", "icon": "check-circle", "shortDescription": "Check competitive and board exam results, download rank cards and marksheets.", "description": "Prompt lookup and downloading of competitive examination results, cut-off lists, scorecards, merit lists, and answer keys.", "keywords": ["result", "scorecard", "rank card", "marksheet"], "documents": ["Roll Number / Registration Number", "Roll Code / Date of Birth"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "college-admission-form", "name": "College Admission Online Application", "category": "College & School Admissions", "icon": "layers", "shortDescription": "Online admission form filling for intermediate (+2), BA, BSc, and BCom courses.", "description": "Guidance and submission assistance for OFSS Bihar Intermediate (+2) admissions and degree college registrations across state universities.", "keywords": ["college admission", "ofss bihar", "inter admission", "degree admission", "ba", "bsc"], "documents": ["10th/12th Marksheet & Admit Card", "CLC / SLC", "Aadhaar Card", "Passport Photo"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "university-ug-pg-admission", "name": "University UG / PG Admission Form", "category": "College & School Admissions", "icon": "award", "shortDescription": "Undergraduate and Postgraduate regular and vocational course admission applications.", "description": "Assistance with university registration portals (Patliputra University, Magadh University, etc.) for BA, BSc, BCom, MA, MSc, and vocational programs.", "keywords": ["university admission", "ug admission", "pg admission", "patliputra", "magadh"], "documents": ["12th/Graduation Marksheet", "Transfer/Migration Certificate", "Aadhaar Card", "Passport Photo"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "school-admission-form", "name": "School Admission & Registration Assistance", "category": "College & School Admissions", "icon": "user-check", "shortDescription": "Assistance with Navodaya, Sainik School, Kendriya Vidyalaya (KV), and board admissions.", "description": "Online form filling for Jawahar Navodaya Vidyalaya (JNVST), Sainik School (AISSEE), and Kendriya Vidyalaya admissions.", "keywords": ["school admission", "navodaya", "jnvst", "sainik school", "kv"], "documents": ["Student Birth Certificate", "Parents' & Student's Aadhaar Cards", "Previous Marksheet", "Passport Photo"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "scholarship-application", "name": "Scholarship Application Assistance (NSP / PMS Bihar)", "category": "College & School Admissions", "icon": "gift", "shortDescription": "National Scholarship Portal (NSP) and Bihar Post Matric Scholarship (PMS) filings.", "description": "Complete guidance for National Scholarship Portal (NSP), Bihar PMS, and Medhasoft including bonafide upload and fee receipt verification.", "keywords": ["scholarship", "nsp", "pms bihar", "post matric", "chhatravritti"], "documents": ["Bonafide Certificate", "College Fee Receipt", "Previous Year Marksheet", "Income, Caste & Domicile Certificates", "Aadhaar-seeded Bank Passbook"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "entrance-exam-application", "name": "Entrance Exam Application (JEE / NEET / CUET / BCECE)", "category": "College & School Admissions", "icon": "zap", "shortDescription": "Registration for JEE Main/Advanced, NEET UG, CUET UG/PG, BCECE, and Polytechnic exams.", "description": "Accurate form submission for engineering, medical, and common university entrance tests with proper center and category choices.", "keywords": ["jee main", "neet", "cuet", "bcece", "polytechnic", "entrance"], "documents": ["10th & 12th Marksheets", "Aadhaar Card", "Passport Photo & Signature", "Category Certificate"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "college-exam-form", "name": "University Semester & Annual Exam Form", "category": "College & School Admissions", "icon": "edit", "shortDescription": "Examination form filling for college and university semester/annual examinations.", "description": "Assistance in filling regular, backlog, and ex-student university examination forms with fee verification and acknowledgment printouts.", "keywords": ["exam form", "semester exam", "university form", "exam fee"], "documents": ["University Registration Slip", "Previous Marksheet", "College ID Card", "Photo & Signature"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "admission-counseling", "name": "Online Admission Counseling Assistance", "category": "College & School Admissions", "icon": "compass", "shortDescription": "College choice filling, seat allotment check, and counseling registration.", "description": "Guidance through counseling phases for BCECE, UGEAC Engineering, NEET Bihar State Quota (UGMAC), and Polytechnic admissions.", "keywords": ["counseling", "choice filling", "seat allotment", "ugeac", "ugmac"], "documents": ["Entrance Exam Rank Card & Admit Card", "10th & 12th Certificates", "Caste & Domicile Certificates"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "migration-academic-doc", "name": "Academic Document & Migration Assistance", "category": "College & School Admissions", "icon": "archive", "shortDescription": "Online application for migration certificates, provisional degrees, and duplicate marksheets.", "description": "Assistance in applying for university migration certificates, provisional degrees, mark-sheet corrections, and verification records online.", "keywords": ["migration certificate", "provisional degree", "duplicate marksheet"], "documents": ["Final Year Marksheet Copy", "Registration Certificate", "College Leaving Certificate (CLC)", "Aadhaar Card"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "pan-card-new", "name": "New PAN Card Application Assistance", "category": "Identity & Legal", "icon": "credit-card", "shortDescription": "Assistance with Form 49A for new physical and e-PAN card applications.", "description": "Guided assistance for new Permanent Account Number (PAN) applications via NSDL/UTIITSL portals for individuals, students, and minors.", "keywords": ["pan card", "new pan", "form 49a", "nsdl", "uti", "e-pan"], "documents": ["Aadhaar Card (matching name & DOB)", "Two Passport Size Photos", "Active Mobile Number for OTP"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "pan-card-correction", "name": "PAN Card Correction & Reprint Assistance", "category": "Identity & Legal", "icon": "refresh-cw", "shortDescription": "Correction of name, date of birth, father's name, or photo on existing PAN cards.", "description": "Assistance with PAN data corrections (CSF Form) to align details with Aadhaar records and reissuing lost or damaged cards.", "keywords": ["pan correction", "pan update", "reprint pan", "lost pan", "pan link"], "documents": ["Existing PAN Card Copy / Number", "Aadhaar Card", "Supporting Proof for Correction", "Passport Photos"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "voter-id-new", "name": "New Voter ID Registration (Form 6)", "category": "Identity & Legal", "icon": "user-plus", "shortDescription": "New voter registration assistance on Election Commission Voter Service Portal.", "description": "Assistance for citizens turning 18 or new voters in submitting Form 6 on the Voter Services portal and tracking enrollment status.", "keywords": ["voter id", "nvsp", "form 6", "new voter", "voter card"], "documents": ["Age Proof (10th Marksheet/Aadhaar)", "Address Proof (Aadhaar/Electricity Bill)", "Passport Photo", "Family Member Voter ID"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "voter-id-correction", "name": "Voter ID Correction & e-EPIC Download (Form 8)", "category": "Identity & Legal", "icon": "check-square", "shortDescription": "Name, address, or photo correction in Voter ID and digital e-EPIC card download.", "description": "Assistance in filing Form 8 for address shifting, data correction, mobile number linking, and instant downloading of digital e-EPIC cards.", "keywords": ["voter id correction", "form 8", "epic download", "voter download"], "documents": ["Existing Voter ID (EPIC) Number", "Aadhaar Card", "Correction Proof", "Linked Mobile Number"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "passport-application-assistance", "name": "Passport Seva Online Application Assistance", "category": "Identity & Legal", "icon": "globe", "shortDescription": "Assistance in filling fresh and reissue Indian Passport applications on Passport Seva.", "description": "Step-by-step guidance for normal/tatkaal passport applications, non-ECR verification, document uploads, and appointment booking.", "keywords": ["passport", "passport seva", "fresh passport", "tatkaal passport"], "documents": ["Aadhaar Card", "10th Passing Certificate (Non-ECR)", "PAN Card / Voter ID", "Bank Passbook / Address Proof"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "passport-appointment", "name": "Passport Office Appointment Scheduling", "category": "Identity & Legal", "icon": "calendar", "shortDescription": "Appointment booking and rescheduling for PSK / POPSK offices.", "description": "Assistance with booking convenience slots, paying official passport appointment fees, slot rescheduling, and receipt generation.", "keywords": ["passport appointment", "psk appointment", "popsk", "arn receipt"], "documents": ["Passport Application Reference Number (ARN)", "Login Credentials"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "aadhaar-assistance", "name": "Aadhaar-Related Online Assistance", "category": "Identity & Legal", "icon": "lock", "shortDescription": "Assistance with official UIDAI online portal services, PVC card ordering, and verification.", "description": "Guidance on UIDAI portal features: ordering official PVC Aadhaar cards, verifying Aadhaar number authenticity, and booking center appointments.", "keywords": ["aadhaar", "uidai", "pvc aadhaar", "aadhaar check", "aadhaar appointment"], "documents": ["Aadhaar Number / EID", "Registered Mobile Number for OTP"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "photo-signature-resize", "name": "Photo & Signature Formatting for Online Forms", "category": "Identity & Legal", "icon": "image", "shortDescription": "Precision cropping, background correction, DPI adjustment, and KB sizing for job portals.", "description": "Specialized photo and signature processing matching exact recruitment portal specifications (KB limits, dimensions, white background, date stamps).", "keywords": ["photo resize", "signature crop", "photo kb converter", "image formatting"], "documents": ["Original Photograph", "Clean Signature on White Paper"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "income-certificate", "name": "Income Certificate Assistance (RTPS Bihar)", "category": "Certificates", "icon": "file-text", "shortDescription": "Online application assistance for Income Certificate (आय प्रमाण पत्र) on RTPS.", "description": "Assistance in drafting and submitting Income Certificate applications at CO/SDO/DM levels via the RTPS Bihar portal.", "keywords": ["income certificate", "aay praman patra", "rtps", "service plus", "bihar rtps"], "documents": ["Aadhaar Card", "Passport Size Photograph", "Self-Declaration of Income", "Active Mobile Number"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "caste-certificate", "name": "Caste Certificate Assistance (RTPS Bihar)", "category": "Certificates", "icon": "user-check", "shortDescription": "Application filing for Caste Certificate (जाति प्रमाण पत्र) for SC, ST, EBC, and BC categories.", "description": "Support for submitting Caste Certificate requests through RTPS Bihar for admission and job reservation requirements.", "keywords": ["caste certificate", "jati praman patra", "rtps bihar", "ebc", "bc", "sc", "st"], "documents": ["Aadhaar Card", "Passport Photo", "Land Record / Family Caste Proof", "Self-Declaration"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "residence-certificate", "name": "Residence Certificate Assistance (RTPS Bihar)", "category": "Certificates", "icon": "map-pin", "shortDescription": "Application assistance for Domicile / Residence Certificate (निवास प्रमाण पत्र).", "description": "Assistance in applying for official permanent residence / domicile certificates via the RTPS portal for examinations and quota eligibility.", "keywords": ["residence certificate", "domicile", "niwas praman patra", "rtps bihar"], "documents": ["Aadhaar Card (with local address)", "Passport Photo", "Electricity Bill / Land Document", "Mobile Number"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "ews-certificate", "name": "EWS Certificate Application Assistance", "category": "Certificates", "icon": "award", "shortDescription": "Economically Weaker Section (EWS) certificate for 10% general category reservation.", "description": "Guidance and online submission assistance for EWS income and asset certificates through state revenue and RTPS portals.", "keywords": ["ews certificate", "economically weaker section", "general reservation", "rtps ews"], "documents": ["Aadhaar Card of Applicant & Family", "Current Year Income Certificate", "Land/Property Document", "Passport Photo"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "obc-ncl-certificate", "name": "OBC Non-Creamy Layer (NCL) Certificate", "category": "Certificates", "icon": "shield", "shortDescription": "State and Central OBC-NCL certificate application for BC/EBC categories.", "description": "Assistance in applying for Non-Creamy Layer (NCL) certificates at CO, SDO, and DM levels for Bihar state and central formats.", "keywords": ["obc ncl", "non creamy layer", "obc certificate", "central obc", "rtps ncl"], "documents": ["Existing Caste & Residence Certificates", "Current Year Income Certificate", "Aadhaar Card", "Self-Declaration Form"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "character-certificate", "name": "Character Certificate Online Assistance", "category": "Certificates", "icon": "check-circle", "shortDescription": "Police verification and character certificate application via Bihar Police RTPS.", "description": "Assistance in applying for official Character Certificates (चरित्र प्रमाण पत्र) through the Bihar Police online verification system.", "keywords": ["character certificate", "police verification", "charitra praman patra"], "documents": ["Aadhaar Card", "Residential Certificate", "Passport Photo", "Matriculation Certificate", "Mobile Number"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "birth-certificate-assistance", "name": "Birth Certificate Application Assistance", "category": "Certificates", "icon": "heart", "shortDescription": "Online application guidance for municipal and block level birth registrations.", "description": "Assistance in compiling documentation and submitting online applications on official civil registration portals (CRS).", "keywords": ["birth certificate", "janam praman patra", "crs portal", "birth registration"], "documents": ["Hospital Birth Summary / Discharge Slip", "Parents' Aadhaar Cards", "Address Proof / Ration Card"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "death-certificate-assistance", "name": "Death Certificate Application Assistance", "category": "Certificates", "icon": "file-minus", "shortDescription": "Application assistance for official civil death certificate registration.", "description": "Assistance in preparing documents, submitting death registration requests on official portals, and downloading certificates.", "keywords": ["death certificate", "mrityu praman patra", "crs portal", "death registration"], "documents": ["Hospital Death Report / Doctor Certificate", "Deceased Aadhaar Card", "Applicant Aadhaar Card"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "electricity-bill-payment", "name": "Electricity Bill Payment Assistance", "category": "Banking & Bill Payments", "icon": "zap", "shortDescription": "Online payment and bill receipt generation for SBPDCL and NBPDCL consumers.", "description": "Fast bill lookup and digital payment assistance for South Bihar Power Distribution Company Limited (SBPDCL) with instant official receipts.", "keywords": ["electricity bill", "sbpdcl", "bijli bill", "light bill", "meter bill"], "documents": ["Consumer Number (CA Number)", "Previous Bill Copy (optional)"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "mobile-dth-recharge", "name": "Mobile & DTH Recharge Assistance", "category": "Banking & Bill Payments", "icon": "smartphone", "shortDescription": "Prepaid and postpaid mobile recharges and DTH television subscription payments.", "description": "Assistance with plan selection, validity packs, and DTH dish recharges across all operators (Jio, Airtel, Vi, BSNL, Tata Play, etc.).", "keywords": ["mobile recharge", "dth recharge", "jio", "airtel", "tata play"], "documents": ["Mobile Number / DTH Customer ID", "Selected Plan Information"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "insurance-premium-payment", "name": "Insurance Premium Payment Assistance", "category": "Banking & Bill Payments", "icon": "shield", "shortDescription": "Online premium payments and receipt downloads for LIC and general insurance.", "description": "Safe online premium payment assistance for Life Insurance Corporation of India (LIC) and general insurance with instant payment receipts.", "keywords": ["lic premium", "insurance payment", "life insurance", "health insurance"], "documents": ["Policy Number", "Date of Birth of Policyholder", "Premium Amount Details"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "bank-account-opening-form", "name": "Online Bank Account Opening Assistance", "category": "Banking & Bill Payments", "icon": "credit-card", "shortDescription": "Assistance in filling online zero-balance and savings account opening forms.", "description": "Guidance for filling digital savings account applications, Jan Dhan inquiries, and video-KYC pre-registration for major banks.", "keywords": ["bank account", "savings account", "zero balance", "sbi account"], "documents": ["Aadhaar Card (linked with mobile)", "PAN Card", "Passport Photo", "Nominee Details"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "pension-life-certificate", "name": "Digital Life Certificate Assistance (Jeevan Pramaan)", "category": "Banking & Bill Payments", "icon": "heart", "shortDescription": "Online Jeevan Pramaan submission and life certificate verification for pensioners.", "description": "Assistance for central, state, and EPFO pensioners in submitting digital life certificates online and verifying PPO numbers.", "keywords": ["jeevan pramaan", "life certificate", "pension certificate", "pensioner"], "documents": ["PPO Number", "Pension Bank Passbook", "Aadhaar Card", "Mobile Number"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "kyc-form-assistance", "name": "Online KYC Form & Update Assistance", "category": "Banking & Bill Payments", "icon": "user-check", "shortDescription": "Assistance with filling re-KYC and document update forms for banks and wallets.", "description": "Support for completing re-KYC forms, updating address and contact information with financial institutions, and document uploads.", "keywords": ["kyc update", "re-kyc", "bank kyc", "kyc document upload"], "documents": ["Bank Account Number", "Aadhaar Card & PAN Card", "Address Proof", "Passport Photo"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "fastag-recharge", "name": "FASTag Purchase & Recharge Assistance", "category": "Banking & Bill Payments", "icon": "navigation", "shortDescription": "Toll FASTag recharge and new vehicle FASTag application support.", "description": "Instant online balance recharge for vehicle FASTag across all issuing banks and assistance in purchasing new electronic toll tags.", "keywords": ["fastag", "fastag recharge", "toll recharge", "nhai fastag"], "documents": ["Vehicle Registration Number (RC)", "FASTag Provider Details"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "water-gas-bill-payment", "name": "LPG Gas Booking & Utility Payment", "category": "Banking & Bill Payments", "icon": "home", "shortDescription": "LPG cylinder refill booking (Indane, HP, Bharat Gas) and water bill payments.", "description": "Online booking of cooking gas cylinders, checking subsidy status, downloading receipts, and municipal water charge payments.", "keywords": ["gas booking", "lpg cylinder", "indane gas", "hp gas", "bharat gas"], "documents": ["LPG Consumer Number / Gas Passbook", "Registered Mobile Number"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "udyam-msme-registration", "name": "Udyam / MSME Registration Assistance", "category": "Business Services", "icon": "briefcase", "shortDescription": "Online application for Government Udyam MSME certificate for small businesses.", "description": "Assistance for shop owners, traders, and small business enterprises in applying for free central government Udyam MSME registration.", "keywords": ["udyam", "msme registration", "udyam certificate", "shop registration"], "documents": ["Owner Aadhaar Card (linked with mobile)", "PAN Card", "Business Name & Address", "Bank Account Details"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "gst-online-assistance", "name": "GST Online Portal Assistance", "category": "Business Services", "icon": "file-text", "shortDescription": "Assistance in navigating the GST portal, form submission, and tax challan creation.", "description": "Assistance in generating GST payment challans, downloading registration certificates, and checking taxpayer status on GSTN.", "keywords": ["gst", "gst challan", "gst portal", "gst certificate"], "documents": ["GSTIN Number / Credentials", "Business PAN Card", "Challan Details"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "trade-license-assistance", "name": "Municipal Trade License Assistance", "category": "Business Services", "icon": "home", "shortDescription": "Application assistance for municipal corporation trade license and shop establishment.", "description": "Guidance on compiling documents and submitting online trade license applications for retail shops and commercial establishments.", "keywords": ["trade license", "shop license", "nagar nigam", "municipal license"], "documents": ["Shop Address Proof (Rent Agreement/Bill)", "Proprietor Aadhaar & PAN Card", "Shop Front Photo with Board"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "business-document-typing", "name": "Professional Document Typing (Hindi & English)", "category": "Business Services", "icon": "edit", "shortDescription": "Accurate computer typing in Hindi (KrutiDev / Remington / Unicode) and English.", "description": "Expert word processing and typing for business proposals, formal applications, affidavits, legal notices, rent agreements, and letters.", "keywords": ["typing", "hindi typing", "english typing", "document typing"], "documents": ["Draft / Handwritten Content or Rough Notes"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "invoice-bill-formatting", "name": "Business Invoice & Quotation Formatting", "category": "Business Services", "icon": "layers", "shortDescription": "Custom design and formatting of professional billing estimates, invoices, and vouchers.", "description": "Creation and formatting of clean Excel/PDF invoices, cash memos, quotations, and payment vouchers customized with your business branding.", "keywords": ["invoice format", "bill formatting", "quotation format", "cash memo"], "documents": ["Business Name & Contact Details", "Item & Pricing Breakdown"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "food-fssai-assistance", "name": "FSSAI Basic Food Registration Assistance", "category": "Business Services", "icon": "shield", "shortDescription": "FSSAI FoSCoS portal application assistance for food stalls, canteens, and sweet shops.", "description": "Guidance on obtaining basic FSSAI food business registration, document compilation, and online certificate download.", "keywords": ["fssai", "food license", "foscos", "food registration"], "documents": ["Applicant Photo", "Aadhaar Card / Govt ID Proof", "Business Address Proof"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "epf-uan-assistance", "name": "EPFO / UAN Online Services Assistance", "category": "Other Online Services", "icon": "award", "shortDescription": "UAN activation, EPF passbook download, and online claim withdrawal guidance.", "description": "Assistance for salaried employees with Member e-Sewa portal: UAN activation, passbook download, KYC seeding, and online transfer claims.", "keywords": ["epf", "uan", "pf balance", "pf passbook", "epfo claim"], "documents": ["UAN Number / Member ID", "Aadhaar Linked Mobile Number", "Bank Account & Cancelled Cheque"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "esham-card-assistance", "name": "e-Shram Card Registration Assistance", "category": "Other Online Services", "icon": "user-check", "shortDescription": "National database registration for unorganized workers (NDUW).", "description": "Assistance in registering unorganized workers on the e-Shram portal, generating 12-digit UAN cards, and updating bank/skill details.", "keywords": ["eshram", "e-shram card", "shramik card", "labour card"], "documents": ["Aadhaar Card", "Aadhaar Linked Mobile Number", "Bank Account Details", "Nominee Details"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "pm-kisan-assistance", "name": "PM-Kisan Samman Nidhi Online Support", "category": "Other Online Services", "icon": "gift", "shortDescription": "Farmer registration, e-KYC verification, and installment status check on PM-Kisan.", "description": "Assistance for eligible farmers: new farmer registration, OTP/Biometric e-KYC completion, Aadhaar correction, and land detail seeding.", "keywords": ["pm kisan", "kisan samman nidhi", "pm kisan ekyc", "farmer scheme"], "documents": ["Aadhaar Card (linked with mobile)", "Land Record (LPC / Khatiyan / Jamabandi)", "Bank Passbook"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "ayushman-card-assistance", "name": "Ayushman Bharat PM-JAY Card Assistance", "category": "Other Online Services", "icon": "heart", "shortDescription": "Eligibility check and e-KYC for Ayushman Golden Health Card (₹5 Lakh Cover).", "description": "Assistance in verifying family eligibility in SECC/Ration Card database, completing e-KYC on the Setu portal, and downloading official Ayushman cards.", "keywords": ["ayushman card", "pm jay", "golden card", "health card", "ayushman bharat"], "documents": ["Ration Card (NFSA) / PM Letter", "Aadhaar Card", "Aadhaar Linked Mobile Number"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "ration-card-online", "name": "Ration Card Online Application & Modification", "category": "Other Online Services", "icon": "home", "shortDescription": "Application for new ration card (RCMS Bihar) and member addition/correction.", "description": "Assistance in filling Form A for new ration cards, adding new family members (Form B), updating address, and downloading electronic ration cards.", "keywords": ["ration card", "rcms bihar", "epds", "new ration card", "ration card list"], "documents": ["Family Group Photo", "Aadhaar Cards of All Family Members", "Bank Passbook of Head of Family", "Residential Certificate"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "driving-license-assistance", "name": "Driving License & Sarathi Online Assistance", "category": "Other Online Services", "icon": "navigation", "shortDescription": "Learner License (LL) and Permanent Driving License (DL) slot booking on Sarathi.", "description": "Guidance on Parivahan Sarathi: online LL test application, fee payment, slot booking, DL renewal, and international driving permit assistance.", "keywords": ["driving license", "sarathi parivahan", "learner license", "dl slot booking"], "documents": ["Aadhaar Card", "Age Proof (10th Marksheet)", "Passport Photo & Signature", "Medical Certificate (Form 1A if required)"], "fee": null, "processingTime": null, "featured": true, "active": true},
  {"id": "vehicle-rc-chalan-payment", "name": "Traffic e-Challan & Vehicle Tax Payment", "category": "Other Online Services", "icon": "zap", "shortDescription": "Online verification and instant payment of traffic e-challans and road taxes.", "description": "Instant lookup of pending traffic police e-challans via Parivahan eChallan, online payment receipt generation, and road tax payments.", "keywords": ["echallan", "traffic challan", "vehicle tax", "parivahan challan"], "documents": ["Vehicle Registration Number (RC)", "Challan Number (if available)"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "police-verification-online", "name": "Police Verification Certificate (PCC) Online", "category": "Other Online Services", "icon": "shield", "shortDescription": "Online application assistance for passport PCC and job police clearances.", "description": "Assistance in applying for Police Clearance Certificates (PCC) for overseas employment, visa requirements, and private security verification.", "keywords": ["police verification", "pcc", "police clearance", "job verification"], "documents": ["Passport Copy (for visa PCC)", "Aadhaar Card", "Residential Certificate", "Passport Photos"], "fee": null, "processingTime": null, "featured": false, "active": true},
  {"id": "rti-online-filing", "name": "RTI Online Application Assistance", "category": "Other Online Services", "icon": "file-text", "shortDescription": "Right to Information (RTI) online drafting and submission for government bodies.", "description": "Assistance in drafting clear, precise RTI queries on central and state RTI portals, online fee payment, and tracking appeal hearings.", "keywords": ["rti", "right to information", "rti online", "rti filing"], "documents": ["Identification Details", "Specific Query / Department Details"], "fee": null, "processingTime": null, "featured": false, "active": true}
]);

// In-Memory Dynamic Runtime Cache
let DYNAMIC_SERVICES_CACHE = [...SERVICES_DATA];
let isDynamicSynced = false;

// Load local overrides if stored by Admin offline
try {
  const localOverrides = localStorage.getItem('maa_dynamic_services');
  if (localOverrides) {
    const parsed = JSON.parse(localOverrides);
    if (Array.isArray(parsed) && parsed.length > 0) {
      const mergedMap = new Map();
      SERVICES_DATA.forEach(s => mergedMap.set(s.id, { ...s }));
      parsed.forEach(s => mergedMap.set(s.id, { ...s }));
      DYNAMIC_SERVICES_CACHE = Array.from(mergedMap.values());
    }
  }
} catch (e) {}

/**
 * Synchronize Services with Firestore (collection 'services')
 * Updates the runtime cache with live services created/edited by Admin.
 * @returns {Promise<Array<Object>>}
 */
async function syncServicesWithFirestore() {
  try {
    if (window.FirebaseApp && window.FirebaseApp.db) {
      const { db, collection, getDocs } = window.FirebaseApp;
      const snap = await getDocs(collection(db, 'services'));
      if (!snap.empty) {
        const firestoreMap = new Map();
        SERVICES_DATA.forEach(s => firestoreMap.set(s.id, { ...s }));
        
        snap.forEach(docSnap => {
          const data = docSnap.data();
          firestoreMap.set(docSnap.id, {
            id: docSnap.id,
            ...data
          });
        });

        DYNAMIC_SERVICES_CACHE = Array.from(firestoreMap.values());
        isDynamicSynced = true;
        
        try {
          localStorage.setItem('maa_dynamic_services', JSON.stringify(DYNAMIC_SERVICES_CACHE));
        } catch (err) {}

        return DYNAMIC_SERVICES_CACHE;
      }
    }
  } catch (err) {
    console.warn('[Services] Firestore dynamic sync notice (Using baseline catalog):', err.message);
  }
  return DYNAMIC_SERVICES_CACHE;
}

/**
 * SVG Icons Mapping
 */
function getServiceIconSvg(iconName) {
  const icons = {
    'briefcase': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"></rect><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"></path></svg>',
    'file-text': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>',
    'navigation': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="3 11 22 2 13 21 11 13 3 11"></polygon></svg>',
    'dollar-sign': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="1" x2="12" y2="23"></line><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>',
    'shield': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>',
    'award': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="7"></circle><polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"></polyline></svg>',
    'check-square': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path></svg>',
    'book-open': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"></path><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"></path></svg>',
    'download': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>',
    'check-circle': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>',
    'layers': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>',
    'user-check': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="8.5" cy="7" r="4"></circle><polyline points="17 11 19 13 23 9"></polyline></svg>',
    'gift': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 12 20 22 4 22 4 12"></polyline><rect x="2" y="7" width="20" height="5"></rect><line x1="12" y1="22" x2="12" y2="7"></line><path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z"></path><path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z"></path></svg>',
    'zap': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon></svg>',
    'edit': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>',
    'compass': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"></polygon></svg>',
    'archive': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="21 8 21 21 3 21 3 8"></polyline><rect x="1" y="3" width="22" height="5"></rect><line x1="10" y1="12" x2="14" y2="12"></line></svg>',
    'credit-card': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="1" y="4" width="22" height="16" rx="2" ry="2"></rect><line x1="1" y1="10" x2="23" y2="10"></line></svg>',
    'refresh-cw': '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="23 4 23 10 17 10"></polyline><polyline points="1 20 1 14 7 14"></polyline><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4
